# -*- coding: utf-8 -*-
"""LSTM on BTC USD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zx2wp1cGnYOTpjuuJ2B3cnCkdOXx2VTp
"""



"""# Task
Create an LSTM model to forecast the next hour's value for BTC-USD using data fetched from yfinance.

## Install Libraries

### Subtask:
Install necessary libraries: yfinance, pandas, numpy, scikit-learn, and tensorflow.

**Reasoning**:
Install the `yfinance` library using pip.
"""

import sys
!{sys.executable} -m pip install yfinance
print("yfinance installed successfully!")

"""**Reasoning**:
Install the `pandas` library using pip.


"""

import sys
!{sys.executable} -m pip install pandas
print("pandas installed successfully!")

"""**Reasoning**:
Install the `numpy` library using pip.


"""

import sys
!{sys.executable} -m pip install numpy
print("numpy installed successfully!")

"""**Reasoning**:
Install the `scikit-learn` library using pip.


"""

import sys
!{sys.executable} -m pip install scikit-learn
print("scikit-learn installed successfully!")

"""**Reasoning**:
Install the `tensorflow` library using pip.


"""

import sys
!{sys.executable} -m pip install tensorflow
print("tensorflow installed successfully!")

"""## Fetch Data

### Subtask:
Fetch hourly historical data for BTC-USD using yfinance.

**Reasoning**:
Import the `yfinance` library to interact with Yahoo Finance data.
"""

import yfinance as yf
print("yfinance imported successfully!")

"""**Reasoning**:
Define the ticker symbol, specify a date range, fetch hourly historical data for BTC-USD using `yfinance.download()`, and then display the first few rows of the resulting DataFrame to inspect the data.


"""

import pandas as pd
import datetime

ticker_symbol = 'BTC-USD'

# Define the end date as today
end_date = datetime.date.today()
# Define the start date as 5 years prior to today, as yfinance hourly data can be limited.
start_date = end_date - datetime.timedelta(days=5*365)

# Fetch hourly data
df_btc = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1h')

print(f"Fetched data for {ticker_symbol} from {start_date} to {end_date}.")
print("First 5 rows of the DataFrame:")
print(df_btc.head())

"""**Reasoning**:
The previous attempt to fetch hourly data failed because yfinance limits hourly data to the last 730 days. To fix this, the `start_date` needs to be adjusted to be within this 730-day limit, specifically 729 days from the `end_date`.


"""

import pandas as pd
import datetime

ticker_symbol = 'BTC-USD'

# Define the end date as today
end_date = datetime.date.today()
# Define the start date as 729 days prior to today, as yfinance hourly data is limited to the last 730 days.
start_date = end_date - datetime.timedelta(days=729)

# Fetch hourly data
df_btc = yf.download(ticker_symbol, start=start_date, end=end_date, interval='1h')

print(f"Fetched data for {ticker_symbol} from {start_date} to {end_date}.")
print("First 5 rows of the DataFrame:")
print(df_btc.head())

"""**Reasoning**:
The data has been successfully fetched. Now, it's essential to preprocess the data, starting with checking for and handling any missing values, which could negatively impact model training. Additionally, simplifying the column names will make the DataFrame easier to work with.


"""

print('Missing values before preprocessing:')
print(df_btc.isnull().sum())

# Drop rows with any missing values. For time series, forward fill or interpolation might be considered, but dropping is a simple first step.
df_btc.dropna(inplace=True)

# Flatten MultiIndex columns for easier access if they exist
if isinstance(df_btc.columns, pd.MultiIndex):
    df_btc.columns = ['_'.join(col).strip() for col in df_btc.columns.values]
    # yfinance often returns columns like 'Close_BTC-USD', 'Volume_BTC-USD'. Let's rename them for clarity.
    df_btc.columns = [col.replace(f'_{ticker_symbol}', '') for col in df_btc.columns]

print('\nMissing values after dropping NaNs:')
print(df_btc.isnull().sum())
print('\nFirst 5 rows of the preprocessed DataFrame:')
print(df_btc.head())

"""## Preprocess Data

### Subtask:
Clean the data, handle missing values, scale features, and create input sequences for the LSTM model.

**Reasoning**:
The first instruction is to select the 'Close' column and scale the data using `MinMaxScaler`. This involves importing `MinMaxScaler`, selecting the relevant column, fitting and transforming the data.
"""

from sklearn.preprocessing import MinMaxScaler
import numpy as np

# Select the 'Close' column for forecasting
data_to_scale = df_btc['Close'].values.reshape(-1, 1)

# Initialize MinMaxScaler and scale the data between 0 and 1
scaler = MinMaxScaler(feature_range=(0, 1))
scaled_data = scaler.fit_transform(data_to_scale)

print("Shape of scaled_data:", scaled_data.shape)
print("First 5 scaled data points:\n", scaled_data[:5])

"""**Reasoning**:
Now that the data is scaled, I will define the `look_back` period and then create the input sequences (X) and corresponding output values (y) for the LSTM model. Finally, these lists will be converted into NumPy arrays and X will be reshaped to the 3-dimensional format required by LSTMs.


"""

look_back = 24 # Use 24 previous hours to predict the next hour

# Create sequences for LSTM model
def create_dataset(dataset, look_back=1):
    X, Y = [], []
    for i in range(len(dataset) - look_back):
        a = dataset[i:(i + look_back), 0]
        X.append(a)
        Y.append(dataset[i + look_back, 0])
    return np.array(X), np.array(Y)

X, y = create_dataset(scaled_data, look_back)

# Reshape input to be [samples, time steps, features] which is required for LSTM
X = np.reshape(X, (X.shape[0], X.shape[1], 1))

print("Shape of X (input sequences):", X.shape)
print("Shape of y (output values):", y.shape)
print("First 5 X sequences:\n", X[:5])
print("First 5 y values:\n", y[:5])

"""**Reasoning**:
Now, I will split the preprocessed `X` (input sequences) and `y` (output values) into training and testing sets. It's crucial to use a sequential split for time series data to prevent data leakage, ensuring that the model is trained on past data and tested on future data.


"""

train_size = int(len(X) * 0.8)
X_train, X_test = X[0:train_size], X[train_size:len(X)]
y_train, y_test = y[0:train_size], y[train_size:len(y)]

print("Shape of X_train:", X_train.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_test:", y_test.shape)

"""## Build and Compile LSTM Model

### Subtask:
Define the architecture of the LSTM model and compile it.

**Reasoning**:
The first step is to import the necessary components from TensorFlow Keras to define and build the LSTM model. Then, I will initialize the model, add the LSTM layer with specified units and input shape, add the Dense output layer, and finally compile the model with the 'adam' optimizer and 'mean_squared_error' loss function.
"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM

# Initialize the Sequential model
model = Sequential()

# Add the LSTM layer
# units: Number of LSTM units
# input_shape: (time_steps, features) - X_train.shape[1] is time_steps (look_back), 1 is features
model.add(LSTM(units=50, return_sequences=False, input_shape=(X_train.shape[1], 1)))

# Add the output layer (Dense layer for single-step prediction)
model.add(Dense(units=1))

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mean_absolute_error'])

# Print model summary
model.summary()
print("LSTM model defined and compiled successfully!")

"""**Reasoning**:
The previous code block successfully built and compiled the LSTM model. The next logical step is to train the model using the prepared training data. This involves fitting the model to `X_train` and `y_train` for a specified number of epochs and batch size.


"""

history = model.fit(X_train, y_train, epochs=50, batch_size=64, verbose=1, validation_data=(X_test, y_test))
print("Model training complete.")

# Get the last 'look_back' data points from the scaled_data to predict the next value
last_look_back_data = scaled_data[-look_back:]

# Reshape the data to be 3D: [1, look_back, 1] for a single prediction
last_look_back_data = last_look_back_data.reshape(1, look_back, 1)

# Make the prediction for the next hour
predicted_scaled_value = model.predict(last_look_back_data)

# Inverse transform the scaled prediction to get the actual price
predicted_price = scaler.inverse_transform(predicted_scaled_value)

print(f"Predicted next hour's BTC-USD price: ${predicted_price[0][0]:,.2f}")

import datetime
import pandas as pd # Already imported earlier, but good practice to include if used in new cell
import numpy as np # Already imported earlier, but good practice to include if used in new cell

# Get the last timestamp from the fetched data
last_data_timestamp = df_btc.index[-1]

# Define 5 PM on the same day as the last data timestamp, in UTC
target_time = last_data_timestamp.replace(hour=17, minute=0, second=0, microsecond=0)

# If 5 PM today has already passed, set the target for 5 PM tomorrow
if target_time <= last_data_timestamp:
    target_time += datetime.timedelta(days=1)

# Calculate the number of hourly steps needed to reach the target time
# The model predicts the price for the hour *starting* at the predicted timestamp.
# If last data is 04:00, and target is 17:00, we need to predict 05:00, ..., 17:00. This is 13 predictions.
# So, the number of predictions is the difference in hours.
num_predictions_needed = int(np.ceil((target_time - last_data_timestamp).total_seconds() / 3600))

# Initialize with the last 'look_back' data points from the scaled_data
current_look_back_data = scaled_data[-look_back:]

predictions = []
prediction_timestamps = []

for i in range(num_predictions_needed):
    # Reshape the current look_back_data for prediction
    input_for_prediction = current_look_back_data.reshape(1, look_back, 1)

    # Make the prediction for the next hour (suppress verbose output for cleaner loop)
    predicted_scaled_value = model.predict(input_for_prediction, verbose=0)

    # Store the predicted scaled value
    predictions.append(predicted_scaled_value[0][0])

    # Calculate the timestamp for this prediction
    current_prediction_timestamp = last_data_timestamp + datetime.timedelta(hours=i + 1)
    prediction_timestamps.append(current_prediction_timestamp)

    # Update current_look_back_data: remove the oldest value and add the new prediction
    current_look_back_data = np.append(current_look_back_data[1:], predicted_scaled_value, axis=0)

# The final prediction is the last one made in the loop
final_predicted_scaled_value = predictions[-1].reshape(-1, 1)

# Inverse transform the final scaled prediction to get the actual price
predicted_price_5pm = scaler.inverse_transform(final_predicted_scaled_value)

print(f"Predicted BTC-USD price for {prediction_timestamps[-1].strftime('%Y-%m-%d %H:%M %Z')} (closest hour to 5 PM): ${predicted_price_5pm[0][0]:,.2f}")

import matplotlib.pyplot as plt

# Make predictions on the test set
test_predictions = model.predict(X_test)

# Inverse transform the predictions and actual values
test_predictions = scaler.inverse_transform(test_predictions)
y_test_actual = scaler.inverse_transform(y_test.reshape(-1, 1))

# Plot the results
plt.figure(figsize=(15, 6))
plt.plot(y_test_actual, label='Actual Price')
plt.plot(test_predictions, label='Predicted Price')
plt.title('LSTM Model Performance on Test Data (BTC-USD)')
plt.xlabel('Time (hours)')
plt.ylabel('Price (USD)')
plt.legend()
plt.show()

print("Plot showing actual vs. predicted prices generated.")

"""### Save Model

**Reasoning**:
The trained LSTM model needs to be saved locally for future use without requiring retraining. The `model.save()` method will save the model's architecture, weights, and optimizer state to an HDF5 file. This allows for easy loading and deployment of the model later.
"""

model.save('lstm_btc_usd_forecaster.h5')
print("Model saved successfully to 'lstm_btc_usd_forecaster.h5'")

import datetime
import pandas as pd
import numpy as np

# Get the last timestamp from the fetched data
last_data_timestamp = df_btc.index[-1]

# Number of hours to predict
num_predictions_needed = 12

# Initialize with the last 'look_back' data points from the scaled_data
current_look_back_data = scaled_data[-look_back:]

predictions_12_hours = []
prediction_timestamps_12_hours = []

print(f"Predicting BTC-USD price for the next {num_predictions_needed} hours starting from {last_data_timestamp.strftime('%Y-%m-%d %H:%M %Z')}:")

for i in range(num_predictions_needed):
    # Reshape the current look_back_data for prediction
    input_for_prediction = current_look_back_data.reshape(1, look_back, 1)

    # Make the prediction for the next hour (suppress verbose output for cleaner loop)
    predicted_scaled_value = model.predict(input_for_prediction, verbose=0)

    # Store the predicted scaled value
    predictions_12_hours.append(predicted_scaled_value[0][0])

    # Calculate the timestamp for this prediction
    current_prediction_timestamp = last_data_timestamp + datetime.timedelta(hours=i + 1)
    prediction_timestamps_12_hours.append(current_prediction_timestamp)

    # Update current_look_back_data: remove the oldest value and add the new prediction
    current_look_back_data = np.append(current_look_back_data[1:], predicted_scaled_value, axis=0)

# Inverse transform all scaled predictions to get the actual prices
predicted_prices_12_hours = scaler.inverse_transform(np.array(predictions_12_hours).reshape(-1, 1))

for i in range(num_predictions_needed):
    print(f"  Hour {i+1} ({prediction_timestamps_12_hours[i].strftime('%Y-%m-%d %H:%M %Z')}): ${predicted_prices_12_hours[i][0]:,.2f}")